### ISSUE TITLE
dof6 = [m[1], -m[0], m[2], m[5] * math.pi / 180,  m[4] * math.pi / 180, m[3] * math.pi / 180] 

### ISSUE THREAD

**Issue by Anna1015** [SiqiD47/vision2019#1]
I know that m[5], m[4] and m[3] represent EZ, EY and EX. But m[1], -m[0], m[2] means Y, -X and Z ? Why are they arranged in this order？

**Comment by SiqiD47** [comment]
Thank you for contacting me. 
If I remember correctly, m[0] = X, m[1] = Y, m[2] = Z, m[3] = EX, m[4] = EY, m[5] = EZ.
Z-Y-X is the order of how ABB robots work, this is just pre-determined.
